<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="ddrive_yaml" value="$(find diff_drive)/config/ddrive.yaml"/>
    <xacro:property name="yaml_dict" value="${xacro.load_yaml(ddrive_yaml)['/**']['ros__parameters']}"/>
    <xacro:property name="base_width" value="${yaml_dict['base_width']}"/>
    <xacro:property name="wheel_radius" value="${yaml_dict['wheel_radius']}"/>
    <xacro:property name="wheel_thickness" value="${yaml_dict['wheel_thickness']}"/>

    <gazebo reference="top_caster">
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
    </gazebo>

    <gazebo reference="bottom_caster">
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
    </gazebo>

    <gazebo>
        <plugin
            filename="libgz-sim-diff-drive-system.so"
            name="gz::sim::systems::DiffDrive">
            <left_joint>base_to_left_wheel</left_joint>
            <right_joint>base_to_right_wheel</right_joint>
            <wheel_separation>${base_width + wheel_thickness}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>50</odom_publish_frequency>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
        </plugin>

        <plugin
            filename="libgz-sim-joint-state-publisher-system.so"
            name="gz::sim::systems::JointStatePublisher">
        </plugin>
     </gazebo>
</robot>