<robot name="ddrive" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="ddrive_yaml" value="$(find diff_drive)/config/ddrive.yaml"/>
    <xacro:property name="yaml_dict" value="${xacro.load_yaml(ddrive_yaml)['/**']['ros__parameters']}"/>
    <xacro:property name="base_length" value="${yaml_dict['base_length']}"/>
    <xacro:property name="base_width" value="${yaml_dict['base_width']}"/>
    <xacro:property name="base_height" value="${yaml_dict['base_height']}"/>
    <xacro:property name="wheel_radius" value="${yaml_dict['wheel_radius']}"/>
    <xacro:property name="wheel_thickness" value="${yaml_dict['wheel_thickness']}"/>
    <xacro:property name="caster_base_radius" value="${yaml_dict['caster_base_radius']}"/>
    <xacro:property name="caster_wheel_radius" value="${yaml_dict['caster_wheel_radius']}"/>
    <xacro:property name="center_to_wheel" value="${yaml_dict['center_to_wheel']}"/>

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="red">
        <color rgba="0.8 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
    </link>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
    </link>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
    </link>

    <link name="bottom_caster_wheel">
        <visual>
            <geometry>
                <cylinder length="${2*caster_base_radius}" radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${2*caster_base_radius}" radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
    </link>

    <link name="bottom_caster_base">
        <visual>
            <geometry>
                <cylinder length="${wheel_radius - .5*base_height - 2*caster_wheel_radius}" radius="${caster_base_radius}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_radius - .5*base_height - 2*caster_wheel_radius}" radius="${caster_base_radius}"/>
            </geometry>
        </collision>
    </link>

    <link name="top_caster_wheel">
        <visual>
            <geometry>
                <cylinder length="${2*caster_base_radius}" radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${2*caster_base_radius}" radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
    </link>

    <link name="top_caster_base">
        <visual>
            <geometry>
                <cylinder length="${wheel_radius - .5*base_height - 2*caster_wheel_radius}" radius="${caster_base_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_radius - .5*base_height - 2*caster_wheel_radius}" radius="${caster_base_radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_to_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin rpy="${-pi/2} 0 0" xyz="${center_to_wheel} ${.5*base_width} 0"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="base_to_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin rpy="${-pi/2} 0 0" xyz="${center_to_wheel} ${-.5*base_width} 0"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="base_to_bottom_caster" type="continuous">
        <parent link="base_link"/>
        <child link="bottom_caster_base"/>
        <origin xyz="${center_to_wheel} 0 ${-(.5*base_height + .5*(wheel_radius - .5*base_height - 2*caster_wheel_radius))}"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="base_to_top_caster" type="continuous">
        <parent link="base_link"/>
        <child link="top_caster_base"/>
        <origin rpy="${pi} 0 0" xyz="${center_to_wheel} 0 ${.5*base_height + .5*(wheel_radius - .5*base_height - 2*caster_wheel_radius)}"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="bottom_caster_to_wheel" type="continuous">
        <parent link="bottom_caster_base"/>
        <child link="bottom_caster_wheel"/>
        <origin rpy="${-pi/2} 0 0" xyz="0 0 ${-(.5*wheel_radius + .5*(wheel_radius - .5*base_height - 2*caster_wheel_radius))}"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="top_caster_to_wheel" type="continuous">
        <parent link="top_caster_base"/>
        <child link="top_caster_wheel"/>
        <origin rpy="${-pi/2} 0 0" xyz="0 0 ${-(.5*wheel_radius + .5*(wheel_radius - .5*base_height - 2*caster_wheel_radius))}"/>
        <axis xyz= "0 0 1"/>
    </joint>

</robot>