<robot name="ddrive" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="ddrive_yaml" value="$(find diff_drive)/config/ddrive.yaml"/>
    <xacro:property name="yaml_dict" value="${xacro.load_yaml(ddrive_yaml)['/**']['ros__parameters']}"/>
    <xacro:property name="base_length" value="${yaml_dict['base_length']}"/>
    <xacro:property name="base_width" value="${yaml_dict['base_width']}"/>
    <xacro:property name="base_height" value="${yaml_dict['base_height']}"/>
    <xacro:property name="wheel_radius" value="${yaml_dict['wheel_radius']}"/>
    <xacro:property name="wheel_thickness" value="${yaml_dict['wheel_thickness']}"/>
    <xacro:property name="caster_radius" value="${yaml_dict['caster_radius']}"/>
    <xacro:property name="center_to_wheel" value="${yaml_dict['center_to_wheel']}"/>

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="red">
        <color rgba="0.8 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="2" />
            <inertia
                ixx="0.181"
                ixy="0"
                ixz="0"
                iyy="0.681"
                iyz="0"
                izz="0.833"
            />
        </inertial>
    </link>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <inertia
                ixx="0.064375"
                ixy="0"
                ixz="0"
                iyy="0.064375"
                iyz="0"
                izz="0.125"
            />
        </inertial>
    </link>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <inertia
                ixx="0.064375"
                ixy="0"
                ixz="0"
                iyy="0.064375"
                iyz="0"
                izz="0.125"
            />
        </inertial>
    </link>

    <link name="bottom_caster">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <inertia
                ixx="0.01225"
                ixy="0"
                ixz="0"
                iyy="0.01225"
                iyz="0"
                izz="0.01225"
            />
        </inertial>
    </link>

    <link name="top_caster">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <inertia
                ixx="0.01225"
                ixy="0"
                ixz="0"
                iyy="0.01225"
                iyz="0"
                izz="0.01225"
            />
        </inertial>
    </link>

    <joint name="base_to_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin rpy="${-pi/2} 0 0" xyz="${center_to_wheel} ${.5*(base_width + wheel_thickness)} 0"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="base_to_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin rpy="${-pi/2} 0 0" xyz="${center_to_wheel} ${-.5*(base_width + wheel_thickness)} 0"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="base_to_bottom_caster" type="fixed">
        <parent link="base_link"/>
        <child link="bottom_caster"/>
        <origin xyz="${-center_to_wheel} 0 ${-(base_height/2 + caster_radius)}"/>
        <axis xyz= "0 0 1"/>
    </joint>

    <joint name="base_to_top_caster" type="fixed">
        <parent link="base_link"/>
        <child link="top_caster"/>
        <origin xyz="${-center_to_wheel} 0 ${base_height/2 + caster_radius}"/>
        <axis xyz= "0 0 1"/>
    </joint>

</robot>